-- Run this in the Supabase SQL Editor to set up your tables

-- 1. Guild Configs
CREATE TABLE IF NOT EXISTS guild_configs (
  guild_id TEXT PRIMARY KEY,
  prefix TEXT DEFAULT ',',
  log_channel TEXT,
  welcome_channel TEXT,
  welcome_message TEXT,
  level_channel TEXT,
  ticket_category TEXT,
  autorole_id TEXT,
  staff_role TEXT,
  goodbye_channel TEXT,
  goodbye_message TEXT,
  boost_channel TEXT,
  boost_message TEXT,
  voicemaster_channel TEXT,
  voicemaster_category TEXT,
  antinuke_enabled INTEGER DEFAULT 0,
  antiraid_enabled INTEGER DEFAULT 0,
  
  -- Settings Command Columns
  mod_log_channel TEXT,
  jail_channel TEXT,
  muted_role TEXT,
  auto_nick TEXT,
  rmuted_role TEXT,
  dj_role TEXT,
  premium_role TEXT,
  join_log_channel TEXT,
  base_role TEXT,
  imuted_role TEXT,
  jail_message TEXT,
  disable_custom_fms BOOLEAN DEFAULT FALSE,
  autoplay BOOLEAN DEFAULT FALSE,

  extra_data JSONB DEFAULT '{}'::jsonb
);

-- 2. Users (Leveling & Guild Data)
CREATE TABLE IF NOT EXISTS users (
  user_id TEXT,
  guild_id TEXT,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, guild_id)
);

-- 3. Tickets
CREATE TABLE IF NOT EXISTS tickets (
  ticket_id TEXT PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  user_id TEXT,
  channel_id TEXT,
  closed INTEGER DEFAULT 0,
  transcript TEXT,
  anonymous INTEGER DEFAULT 0
);

-- 4. Global Economy Profile
CREATE TABLE IF NOT EXISTS economy (
  user_id TEXT PRIMARY KEY,
  balance INTEGER DEFAULT 0,
  bank INTEGER DEFAULT 0,
  last_daily BIGINT DEFAULT 0,
  last_work BIGINT DEFAULT 0,
  last_rob BIGINT DEFAULT 0,
  rules_accepted INTEGER DEFAULT 0,
  partner_id TEXT,
  bio TEXT,
  marriage_time BIGINT,
  parent_id TEXT,
  children TEXT
);

-- 5. Inventory
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  item_id TEXT,
  count INTEGER DEFAULT 0
);

-- 6. Giveaways
CREATE TABLE IF NOT EXISTS giveaways (
  message_id TEXT PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  channel_id TEXT,
  prize TEXT,
  winners INTEGER,
  end_time INTEGER,
  ended INTEGER DEFAULT 0
);

-- 7. Warns
CREATE TABLE IF NOT EXISTS warns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  user_id TEXT,
  reason TEXT,
  timestamp INTEGER
);

-- 8. AFK System
CREATE TABLE IF NOT EXISTS afk (
  user_id TEXT PRIMARY KEY,
  reason TEXT DEFAULT 'AFK',
  timestamp BIGINT,
  guild_id TEXT
);

-- 9. Logs
CREATE TABLE IF NOT EXISTS logs (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  event TEXT,
  channel_id TEXT,
  PRIMARY KEY (guild_id, event)
);

-- 10. Fake Permissions
CREATE TABLE IF NOT EXISTS fake_permissions (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  role_id TEXT,
  permission TEXT,
  PRIMARY KEY (guild_id, role_id, permission)
);

-- 11. Custom Command Invokes
CREATE TABLE IF NOT EXISTS invokes (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  command TEXT,
  message TEXT,
  PRIMARY KEY (guild_id, command)
);

-- 12. Aliases
CREATE TABLE IF NOT EXISTS aliases (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  alias TEXT,
  command TEXT,
  PRIMARY KEY (guild_id, alias)
);

-- 13. AutoMod
CREATE TABLE IF NOT EXISTS automod (
  guild_id TEXT PRIMARY KEY REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  links INTEGER DEFAULT 0,
  invites INTEGER DEFAULT 0,
  mass_mentions INTEGER DEFAULT 0,
  bad_words INTEGER DEFAULT 0
);

-- 14. Reaction Roles
CREATE TABLE IF NOT EXISTS reaction_roles (
  message_id TEXT,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  channel_id TEXT,
  emoji TEXT,
  role_id TEXT,
  PRIMARY KEY (message_id, emoji)
);

-- 15. Sticky Messages
CREATE TABLE IF NOT EXISTS sticky_messages (
  channel_id TEXT PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  message TEXT,
  last_message_id TEXT
);

-- 16. Auto Responders
CREATE TABLE IF NOT EXISTS autoresponders (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  trigger TEXT,
  reply TEXT,
  match_mode TEXT DEFAULT 'exact',
  PRIMARY KEY (guild_id, trigger)
);

-- 17. Reminders
CREATE TABLE IF NOT EXISTS reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  message TEXT,
  end_time BIGINT,
  channel_id TEXT
);

-- 18. Tags
CREATE TABLE IF NOT EXISTS tags (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  name TEXT,
  content TEXT,
  author_id TEXT,
  created_at BIGINT,
  PRIMARY KEY (guild_id, name)
);

-- 19. Booster Configuration
CREATE TABLE IF NOT EXISTS booster_configs (
  guild_id TEXT PRIMARY KEY REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  base_role TEXT,
  award_role TEXT,
  role_limit INTEGER DEFAULT 1
);

-- 20. Image Only Channels
CREATE TABLE IF NOT EXISTS image_only_channels (
  channel_id TEXT PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE
);

-- 21. Talk Channels
CREATE TABLE IF NOT EXISTS talk_channels (
  channel_id TEXT PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  role_id TEXT
);
